repos:
-   repo: local
    hooks:
    -   id: felint
        name: Lint frontend files
        files: ^frontend/.*\.[jt]sx?$
        types: [file]
        language: system
        entry: ./scripts/lint.sh felint
    -   id: belint
        name: Lint backend files
        files: ^backend/.*\.[jt]sx?$
        types: [file]
        language: system
        entry: ./scripts/lint.sh belint